### ISSUE TITLE
"loadedmetadata" event never fires on otherwise playable video

### ISSUE THREAD

**Issue by kauffj** [feross/render-media#31]
This seems like a weird issue, and apologies in advance if this is an invalid ticket. If we can do more to investigate or clarify this, please let me know.

[This file](https://spee.ch/d/ee-UeSYRg8GsJI.mp4), which plays correctly when embedded directly into a video tag, never has the `loadedmetadata` event fire when played via `render-media`.

Additional information may be available in [this ticket](https://github.com/lbryio/lbry-app/issues/635#issuecomment-333911622).

**Comment by tzarebczan** [comment]
It also fails to stream on instant.io -https://instant.io/#ae8e248aeba47363d0fbe577c9b8b839018f4e79

**Comment by feross** [comment]
👋 Thanks for opening an issue. This project is a volunteer-run effort. I don't have any immediate plans to work on this issue, so I'm going to close it.

However, I noticed you work for a for-profit company. Please consider asking your company to allocate resources toward fixing this issue and submitting a PR. I'll be happy to review any PR you contribute. 😄 

Also, the issue will need to be fixed in [videostream](https://github.com/jhiesey/videostream).

Finally, if you lack the time or skills to fix this issue, you can hire me at my standard hourly rate. Contact me at [[my first name]@feross.org](mailto:) to discuss further.
