### ISSUE TITLE
Accept a web readableStream

### ISSUE THREAD

**Issue by jimmywarting** [feross/render-media#45]
I would like to use this. But I'm using web technologies mostly.
I don't want to transform a fetch readableStream into a node stream

**Comment by feross** [comment]
It's not clear to me how we could support web readable streams without also shipping an implementation of Node.js streams unless we shipped two versions of this package. Since this package was created primarily to serve the WebTorrent use case, and WebTorrent uses `readable-stream` I'm not keen to break compatibility with it.

However, if you have ideas for how to support both types of streams, please share. Perhaps we can update this to accept either type of stream.
